// flow-typed signature: 3519aa6d86a110e08dc4af8265616185
// flow-typed version: <<STUB>>/react-styled-select_v^1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-styled-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-styled-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-styled-select/bin/extract-css-variables' {
  declare module.exports: any;
}

declare module 'react-styled-select/demo/demo.bundle' {
  declare module.exports: any;
}

declare module 'react-styled-select/demo/demo' {
  declare module.exports: any;
}

declare module 'react-styled-select/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/helpers/shadowDOM' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/index' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/polyfill' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/Async' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/constants' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/cssHelpers' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/cssVariables' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/functions/stringifyValue' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/Select' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectArrow' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectArrowZone' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectClear' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectClearZone' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectControl' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectInput' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectInputField' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectInputFieldSize' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectMenu' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectMenuOuter' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectMultiValue' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectMultiValueWrapper' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectNoResults' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectOption' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectPlaceholder' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectValue' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectValueIcon' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectValueLabel' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/partials/SelectValueWrapper' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/renderers/OptionRenderer' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/renderers/ValueRenderer' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/Select' {
  declare module.exports: any;
}

declare module 'react-styled-select/lib/Select/ShadowDOM' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-styled-select/bin/extract-css-variables.js' {
  declare module.exports: $Exports<'react-styled-select/bin/extract-css-variables'>;
}
declare module 'react-styled-select/demo/demo.bundle.js' {
  declare module.exports: $Exports<'react-styled-select/demo/demo.bundle'>;
}
declare module 'react-styled-select/demo/demo.js' {
  declare module.exports: $Exports<'react-styled-select/demo/demo'>;
}
declare module 'react-styled-select/demo/webpack.config.js' {
  declare module.exports: $Exports<'react-styled-select/demo/webpack.config'>;
}
declare module 'react-styled-select/lib/helpers/shadowDOM.js' {
  declare module.exports: $Exports<'react-styled-select/lib/helpers/shadowDOM'>;
}
declare module 'react-styled-select/lib/index.js' {
  declare module.exports: $Exports<'react-styled-select/lib/index'>;
}
declare module 'react-styled-select/lib/polyfill.js' {
  declare module.exports: $Exports<'react-styled-select/lib/polyfill'>;
}
declare module 'react-styled-select/lib/Select/Async.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/Async'>;
}
declare module 'react-styled-select/lib/Select/constants.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/constants'>;
}
declare module 'react-styled-select/lib/Select/cssHelpers.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/cssHelpers'>;
}
declare module 'react-styled-select/lib/Select/cssVariables.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/cssVariables'>;
}
declare module 'react-styled-select/lib/Select/functions/stringifyValue.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/functions/stringifyValue'>;
}
declare module 'react-styled-select/lib/Select/partials/Select.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/Select'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectArrow.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectArrow'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectArrowZone.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectArrowZone'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectClear.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectClear'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectClearZone.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectClearZone'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectControl.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectControl'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectInput.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectInput'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectInputField.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectInputField'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectInputFieldSize.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectInputFieldSize'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectMenu.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectMenu'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectMenuOuter.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectMenuOuter'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectMultiValue.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectMultiValue'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectMultiValueWrapper.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectMultiValueWrapper'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectNoResults.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectNoResults'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectOption.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectOption'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectPlaceholder.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectPlaceholder'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectValue.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectValue'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectValueIcon.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectValueIcon'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectValueLabel.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectValueLabel'>;
}
declare module 'react-styled-select/lib/Select/partials/SelectValueWrapper.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/partials/SelectValueWrapper'>;
}
declare module 'react-styled-select/lib/Select/renderers/OptionRenderer.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/renderers/OptionRenderer'>;
}
declare module 'react-styled-select/lib/Select/renderers/ValueRenderer.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/renderers/ValueRenderer'>;
}
declare module 'react-styled-select/lib/Select/Select.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/Select'>;
}
declare module 'react-styled-select/lib/Select/ShadowDOM.js' {
  declare module.exports: $Exports<'react-styled-select/lib/Select/ShadowDOM'>;
}
