'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var CLARK_PRIMARY = exports.CLARK_PRIMARY = '#EA4900';
var CLARK_SECONDARY = exports.CLARK_SECONDARY = '#413E60';
var CLARK_TERTIARY = exports.CLARK_TERTIARY = '#008489';

var ERROR_PRIMARY = exports.ERROR_PRIMARY = '#fcece5';

var CLARK_ACCENT_PRIMARY = exports.CLARK_ACCENT_PRIMARY = '#56D8DD';
var CLARK_ACCENT_SECONDARY = exports.CLARK_ACCENT_SECONDARY = '#EC8E00';

var TRANSPARENT = exports.TRANSPARENT = 'transparent';
var WHITE = exports.WHITE = '#FFF';
var GREY_10 = exports.GREY_10 = '#ECEBEF';
var GREY_25 = exports.GREY_25 = '#CFCFD7';
var GREY_50 = exports.GREY_50 = '#A09EAF';
var GREY_75 = exports.GREY_75 = '#716f88';
var BLACK = exports.BLACK = '#000';
var TEAL = exports.TEAL = '#398188';

var LINK_COLOR_PRIMARY = exports.LINK_COLOR_PRIMARY = CLARK_TERTIARY;
var LINK_COLOR_SECONDARY = exports.LINK_COLOR_SECONDARY = '#00565a';
var LINK_COLOR_TERTIARY = exports.LINK_COLOR_TERTIARY = GREY_50;
var LINK_COLOR_QUATERNARY = exports.LINK_COLOR_QUATERNARY = GREY_75;

var BORDER_COLOR_PRIMARY = exports.BORDER_COLOR_PRIMARY = GREY_50;
var BORDER_COLOR_SECONDARY = exports.BORDER_COLOR_SECONDARY = GREY_75;

var BACKGROUND_COLOR_PRIMARY = exports.BACKGROUND_COLOR_PRIMARY = GREY_10;
var BACKGROUND_COLOR_SECONDARY = exports.BACKGROUND_COLOR_SECONDARY = '#F4FCFC';
var BACKGROUND_COLOR_TERTIARY = exports.BACKGROUND_COLOR_TERTIARY = '#F9F9FA';

var BUTTON_COLOR_PRIMARY = exports.BUTTON_COLOR_PRIMARY = CLARK_PRIMARY;
var BUTTON_COLOR_SECONDARY = exports.BUTTON_COLOR_SECONDARY = '#FF6B18';
var BUTTON_COLOR_TERTIARY = exports.BUTTON_COLOR_TERTIARY = '#c43d00';

var OPACITY_50 = exports.OPACITY_50 = '50';
var OPACITY_25 = exports.OPACITY_25 = '25';